displayName=Versatile Logger
author=PeppieLangwaus
description=A highly configurable chat logger
tags=chat,logging,webhooks,remote
version=1.0.1
plugins=xyz.peppie.versatilelogger.VersatileLoggerPlugin
build=standard