displayName=Versatile Logger
author=PeppieLangwaus
description=A highly configurable chat logger
tags=chat,logging,webhooks,remote,cc,fc
version=1.0.2
plugins=xyz.peppie.versatilelogger.VersatileLoggerPlugin
build=standard